version: "3.8"

services:
  # Service
  facial_recognition:
    container_name: facial_recognition
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ENV: "pro"
    ports:
      - "${PORT}:${PORT}"
    networks:
      - facial_recognition-network
    healthcheck:
      test:
        ["CMD", "sh", "-c", "curl -sSf http://${HOST}:${PORT}/ping > /dev/null"]
      interval: 60s
      timeout: 2s
      retries: 3

networks:
  facial_recognition-network:
    driver: bridge
